"""initial tables

Revision ID: a39c33530b56
Revises: 
Create Date: 2026-09-14 22:15:16.140835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a39c33530b56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logistics_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('briefing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_mode', sa.String(length=16), nullable=True),
    sa.Column('location_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index('ix_scenarios_created_at', 'scenarios', ['created_at'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('claim_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claim_b', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'key', name='uq_conflicts_scenario_key')
    )
    op.create_index('ix_conflicts_scenario_id', 'conflicts', ['scenario_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_scenario_id_id', 'events', ['scenario_id', 'id'], unique=False)
    op.create_table('negotiation_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conflict_id', 'turn_number', name='uq_turns_conflict_turn')
    )
    op.create_index('ix_negotiation_turns_conflict_id', 'negotiation_turns', ['conflict_id'], unique=False)
    op.create_table('resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('winning_side', sa.String(length=64), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conflict_id')
    )
    op.create_index('ix_resolutions_conflict_id', 'resolutions', ['conflict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resolutions_conflict_id', table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_index('ix_negotiation_turns_conflict_id', table_name='negotiation_turns')
    op.drop_table('negotiation_turns')
    op.drop_index('ix_events_scenario_id_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_conflicts_scenario_id', table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index('ix_scenarios_created_at', table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
